// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CanvasController from "./canvas_controller"
application.register("canvas", CanvasController)

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import WebconsoleController from "./webconsole_controller"
application.register("webconsole", WebconsoleController)
