AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - config/**/*
    - bin/**/*
    - config.ru
    - Rakefile
    - vendor/**/*
    - spec/**/*
  TargetRubyVersion: 3.1.2
  # TargetRailsVersion: 7.0.3
  SuggestExtensions: false

Metrics/MethodLength:
  Max: 25

# Metrics/BlockLength:
#   Enabled: false

Style/Documentation:
  Enabled: false
# Layout/LineLength:
#   Enabled: false

# Metrics/AbcSize:
#   Enabled: false

# Metrics/CyclomaticComplexity:
#   Max: 10